const data = [
  // ===== TRENDING (12 listings) =====
  {
    title: "Oceanfront Penthouse Miami",
    description: "Stunning oceanfront penthouse with panoramic views of the Atlantic. Modern luxury meets beach living in this spacious 3-bedroom retreat. Features floor-to-ceiling windows, private balcony, and direct beach access.",
    image: { filename: "trending-miami-penthouse-1", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=60" },
    price: 4500,
    location: "Miami Beach",
    country: "United States",
    category: "Trending",
    avgRating: 4.8,
    numReviews: 89
  },
  {
    title: "Downtown Loft NYC",
    description: "Chic downtown loft in the heart of Manhattan. Exposed brick walls, industrial design, and stunning city views. Walking distance to top restaurants, museums, and Central Park.",
    image: { filename: "trending-nyc-loft-1", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=60" },
    price: 3200,
    location: "New York City",
    country: "United States",
    category: "Trending",
    avgRating: 4.7,
    numReviews: 156
  },
  {
    title: "Treehouse Big Sur",
    description: "Magical treehouse nestled among giant redwoods. A unique retreat offering complete immersion in nature while maintaining luxury comfort. Features private deck and star-gazing opportunities.",
    image: { filename: "trending-bigsur-treehouse-1", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=60" },
    price: 2800,
    location: "Big Sur",
    country: "United States",
    category: "Trending",
    avgRating: 4.9,
    numReviews: 67
  },
  {
    title: "Glamping Morocco",
    description: "Experience luxury camping in the Sahara Desert. Traditional Berber tent with modern amenities, private campfire dinners, and unforgettable sunrise over the dunes.",
    image: { filename: "trending-morocco-glamping-1", url: "https://images.unsplash.com/photo-1530538309175-4f2a99c49ecb?w=800&q=60" },
    price: 1800,
    location: "Merzouga",
    country: "Morocco",
    category: "Trending",
    avgRating: 4.9,
    numReviews: 45
  },
  {
    title: "Luxury Yacht Dubai",
    description: "Ultra-luxurious yacht experience in Dubai Marina. Full crew, gourmet catering, and exclusive access to Dubai's most iconic views. The ultimate in nautical luxury.",
    image: { filename: "trending-dubai-yacht-1", url: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=60" },
    price: 8500,
    location: "Dubai Marina",
    country: "United Arab Emirates",
    category: "Trending",
    avgRating: 4.8,
    numReviews: 32
  },
  {
    title: "Sky Villa Singapore",
    description: "Award-winning Sky Villa with breathtaking city skyline views. Infinity pool, private gym, and 24-hour concierge service. The pinnacle of urban luxury living.",
    image: { filename: "trending-singapore-villa-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=60" },
    price: 6200,
    location: "Marina Bay",
    country: "Singapore",
    category: "Trending",
    avgRating: 4.7,
    numReviews: 78
  },
  {
    title: "Ice Hotel Sweden",
    description: "Sleep in the world's most famous ice hotel. Hand-carved ice rooms, thermal sleeping bags, and surreal Arctic landscape. A once-in-a-lifetime winter experience.",
    image: { filename: "trending-sweden-ice-1", url: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=800&q=60" },
    price: 2400,
    location: "Jukkasjärvi",
    country: "Sweden",
    category: "Trending",
    avgRating: 4.6,
    numReviews: 58
  },
  {
    title: "Cave House Spain",
    description: "Unique cave dwelling in Granada's historic Albaicín. Carved into the hillside with stunning Alhambra views. Authentic Andalusian architecture with modern comfort.",
    image: { filename: "trending-spain-cave-1", url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=60" },
    price: 1650,
    location: "Granada",
    country: "Spain",
    category: "Trending",
    avgRating: 4.8,
    numReviews: 93
  },
  {
    title: "Floating House Amsterdam",
    description: "Iconic houseboat on Amsterdam's most beautiful canal. Fully renovated with modern amenities while maintaining original character. Experience true Dutch living.",
    image: { filename: "trending-amsterdam-boat-1", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=60" },
    price: 2100,
    location: "Amsterdam",
    country: "Netherlands",
    category: "Trending",
    avgRating: 4.7,
    numReviews: 124
  },
  {
    title: "Bubble Hotel France",
    description: "Transparent bubble accommodation in the French Alps. Sleep under the stars in complete comfort. Includes breakfast delivered by balloon basket. Magical experience.",
    image: { filename: "trending-france-bubble-1", url: "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=60" },
    price: 1900,
    location: "Chamonix",
    country: "France",
    category: "Trending",
    avgRating: 4.9,
    numReviews: 41
  },
  {
    title: "Lakefront Sauna Finland",
    description: "Authentic Finnish lakeside sauna experience. Private lakeside location with traditional smoke sauna, hot tub, and Arctic wildlife. Pure relaxation in nature.",
    image: { filename: "trending-finland-sauna-1", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=60" },
    price: 1500,
    location: "Kuopio",
    country: "Finland",
    category: "Trending",
    avgRating: 4.8,
    numReviews: 56
  },
  {
    title: "Helicopter Pad Monaco",
    description: "Exclusive rooftop penthouse with private helicopter landing pad. Ultimate Monaco luxury with harbor views, infinity pool, and 5-star concierge. The ultimate VIP experience.",
    image: { filename: "trending-monaco-heli-1", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=60" },
    price: 12000,
    location: "Monte Carlo",
    country: "Monaco",
    category: "Trending",
    avgRating: 4.9,
    numReviews: 23
  },

  // ===== ROOMS (12 listings) =====
  {
    title: "Cozy Room Paris Attic",
    description: "Charming attic room in Le Marais with Eiffel Tower views. Original beams, exposed stone, and authentic Parisian character. Perfect for couples seeking romance.",
    image: { filename: "rooms-paris-attic-1", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=60" },
    price: 1200,
    location: "Paris",
    country: "France",
    category: "Rooms",
    avgRating: 4.7,
    numReviews: 87
  },
  {
    title: "Modern Loft Room Barcelona",
    description: "Stylish room in a converted textile factory. Industrial chic design with private terrace. Located in trendy El Poblenec with best restaurants steps away.",
    image: { filename: "rooms-barcelona-loft-1", url: "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800&q=60" },
    price: 950,
    location: "Barcelona",
    country: "Spain",
    category: "Rooms",
    avgRating: 4.6,
    numReviews: 112
  },
  {
    title: "Traditional Ryokan Kyoto",
    description: "Authentic Japanese ryokan room with tatami floors and futon bedding. Traditional onsen bath, kaiseki dinner, and serene garden views. Timeless Japanese hospitality.",
    image: { filename: "rooms-kyoto-ryokan-1", url: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=60" },
    price: 2100,
    location: "Kyoto",
    country: "Japan",
    category: "Rooms",
    avgRating: 4.9,
    numReviews: 145
  },
  {
    title: "Boutique Room Santorini",
    description: "Romantic cave room in Oia with caldera views. White-washed walls, curved arches, and stunning sunset views. The most photographed village in Greece.",
    image: { filename: "rooms-santorini-boutique-1", url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=60" },
    price: 2800,
    location: "Oia",
    country: "Greece",
    category: "Rooms",
    avgRating: 4.8,
    numReviews: 98
  },
  {
    title: "Castle Room Scotland",
    description: "Dramatic room in a 16th-century Scottish castle. Four-poster bed, original stone walls, and Highland views. Fairytale accommodation with modern luxury.",
    image: { filename: "rooms-scotland-castle-1", url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&q=60" },
    price: 1850,
    location: "Inverness",
    country: "United Kingdom",
    category: "Rooms",
    avgRating: 4.7,
    numReviews: 76
  },
  {
    title: "Beach Hut Bali",
    description: "Simple beach hut with extraordinary ocean views. Steps from the sand, perfect for surfers and beach lovers. Authentic Bali relaxed vibes.",
    image: { filename: "rooms-bali-hut-1", url: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800&q=60" },
    price: 450,
    location: "Canggu",
    country: "Indonesia",
    category: "Rooms",
    avgRating: 4.5,
    numReviews: 203
  },
  {
    title: "Mountain Lodge Room Aspen",
    description: "Ski-in/ski-out room at premier Aspen resort. Fireplace, mountain views, and access to world-class skiing. Ultimate winter luxury in the Rockies.",
    image: { filename: "rooms-aspen-lodge-1", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=800&q=60" },
    price: 2500,
    location: "Aspen",
    country: "United States",
    category: "Rooms",
    avgRating: 4.8,
    numReviews: 64
  },
  {
    title: "Urban Room Tokyo Capsule",
    description: "Innovative capsule room in Shinjuku. Ultra-compact but perfectly designed with high-tech features. Experience the future of Japanese urban living.",
    image: { filename: "rooms-tokyo-capsule-1", url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&q=60" },
    price: 350,
    location: "Tokyo",
    country: "Japan",
    category: "Rooms",
    avgRating: 4.4,
    numReviews: 312
  },
  {
    title: "Hostel Private Prague",
    description: "Private room in award-winning Prague hostel. Beautiful Art Nouveau building with modern amenities. Perfect balance of budget and comfort.",
    image: { filename: "rooms-prague-hostel-1", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=60" },
    price: 550,
    location: "Prague",
    country: "Czech Republic",
    category: "Rooms",
    avgRating: 4.6,
    numReviews: 187
  },
  {
    title: "Farm Stay Room Tuscany",
    description: "Rustic room on working Tuscan farm. Olive groves, vineyards, and homemade breakfast. Authentic Italian countryside experience at its finest.",
    image: { filename: "rooms-tuscany-farm-1", url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=60" },
    price: 1100,
    location: "Chianti",
    country: "Italy",
    category: "Rooms",
    avgRating: 4.8,
    numReviews: 134
  },
  {
    title: "Ski Chalet Room Alps",
    description: "Cozy room in classic Alpine chalet. Wood-paneled walls, warm atmosphere, and ski-in access. Perfect for winter sports enthusiasts seeking comfort.",
    image: { filename: "rooms-alps-chalet-1", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=60" },
    price: 1450,
    location: "Zermatt",
    country: "Switzerland",
    category: "Rooms",
    avgRating: 4.7,
    numReviews: 92
  },
  {
    title: "Tree Room Costa Rica",
    description: "Elevated tree room in Costa Rican rainforest. Howler monkeys, toucans, and complete nature immersion. Eco-luxury in one of the world's most biodiverse regions.",
    image: { filename: "rooms-costarica-tree-1", url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=60" },
    price: 980,
    location: "Monteverde",
    country: "Costa Rica",
    category: "Rooms",
    avgRating: 4.9,
    numReviews: 78
  },

  // ===== APARTMENTS (12 listings) =====
  {
    title: "Tuscan Villa Apartment",
    description: "Luxurious apartment in historic Tuscan villa. Terracotta floors, vaulted ceilings, and panoramic vineyard views. The essence of Italian elegance.",
    image: { filename: "apartments-florence-villa-1", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=60" },
    price: 2200,
    location: "Florence",
    country: "Italy",
    category: "Apartments",
    avgRating: 4.8,
    numReviews: 156
  },
  {
    title: "Amsterdam Canal House",
    description: "Classic Dutch canal house apartment. Original features, modern kitchen, and prime Grachten view. Iconic Amsterdam experience in historic building.",
    image: { filename: "apartments-amsterdam-canal-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=60" },
    price: 1950,
    location: "Amsterdam",
    country: "Netherlands",
    category: "Apartments",
    avgRating: 4.7,
    numReviews: 189
  },
  {
    title: "London Thames View",
    description: "Contemporary apartment with uninterrupted Thames views. Floor-to-ceiling windows, designer interior, and walk to Big Ben. London living at its best.",
    image: { filename: "apartments-london-thames-1", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=60" },
    price: 3500,
    location: "London",
    country: "United Kingdom",
    category: "Apartments",
    avgRating: 4.6,
    numReviews: 234
  },
  {
    title: "Berlin Industrial Loft",
    description: "Hip converted factory loft in Kreuzberg. Exposed brick, steel beams, and artistic vibe. Trendy neighborhood with legendary nightlife.",
    image: { filename: "apartments-berlin-loft-1", url: "https://images.unsplash.com/photo-1600210492493-0946913c3316?w=800&q=60" },
    price: 1400,
    location: "Berlin",
    country: "Germany",
    category: "Apartments",
    avgRating: 4.7,
    numReviews: 167
  },
  {
    title: "Tokyo Micro Apartment",
    description: "Cleverly designed micro apartment in Shibuya. Every inch optimized for comfort. Walking distance to everything Tokyo offers. Modern minimalism.",
    image: { filename: "apartments-tokyo-micro-1", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=60" },
    price: 1100,
    location: "Tokyo",
    country: "Japan",
    category: "Apartments",
    avgRating: 4.5,
    numReviews: 278
  },
  {
    title: "Paris Haussmann Apartment",
    description: "Classic Haussmann apartment in the 7th Arrondissement. Period details, balcony views of Eiffel Tower, and elegance. Parisian sophistication.",
    image: { filename: "apartments-paris-haussmann-1", url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=60" },
    price: 2800,
    location: "Paris",
    country: "France",
    category: "Apartments",
    avgRating: 4.9,
    numReviews: 145
  },
  {
    title: "Madrid Historic Flat",
    description: "Beautifully restored flat in La Latina. Original tiles, wooden beams, and rooftop terrace. Steps from Plaza Mayor and tapas bars.",
    image: { filename: "apartments-madrid-flat-1", url: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec3?w=800&q=60" },
    price: 1350,
    location: "Madrid",
    country: "Spain",
    category: "Apartments",
    avgRating: 4.7,
    numReviews: 123
  },
  {
    title: "Lisbon Ocean View",
    description: "Bright apartment in Principe Real with Tagus views. Contemporary design, shared pool, and tram 28 at door. Best of Lisbon living.",
    image: { filename: "apartments-lisbon-ocean-1", url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=60" },
    price: 1600,
    location: "Lisbon",
    country: "Portugal",
    category: "Apartments",
    avgRating: 4.8,
    numReviews: 198
  },
  {
    title: "Vienna Art Nouveau",
    description: "Stunning Art Nouveau apartment in inner city. Period details, high ceilings, and museum district location. Habsburg elegance meets modern comfort.",
    image: { filename: "apartments-vienna-artnouveau-1", url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=60" },
    price: 1850,
    location: "Vienna",
    country: "Austria",
    category: "Apartments",
    avgRating: 4.7,
    numReviews: 89
  },
  {
    title: "Budapest Thermal Bath View",
    description: "Elegant apartment overlooking Szechenyi Baths. Danube views, spa access, and ruin bar neighborhood. Budapest's best at your doorstep.",
    image: { filename: "apartments-budapest-thermal-1", url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=60" },
    price: 1200,
    location: "Budapest",
    country: "Hungary",
    category: "Apartments",
    avgRating: 4.6,
    numReviews: 176
  },
  {
    title: "Stockholm Fika Apartment",
    description: "Cozy apartment in Vasastan with Stockholm vibe. Classic Swedish design, breakfast included, and archipelago day trips. Nordic comfort.",
    image: { filename: "apartments-stockholm-fika-1", url: "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=800&q=60" },
    price: 1750,
    location: "Stockholm",
    country: "Sweden",
    category: "Apartments",
    avgRating: 4.8,
    numReviews: 112
  },
  {
    title: "Copenhagen Hygge Flat",
    description: "Classic Copenhagen flat in trendy Nørrebro. Danish design, candlelit dinners, and bicycle included. Experience true Danish hygge lifestyle.",
    image: { filename: "apartments-copenhagen-hygge-1", url: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=60" },
    price: 1900,
    location: "Copenhagen",
    country: "Denmark",
    category: "Apartments",
    avgRating: 4.9,
    numReviews: 134
  },

  // ===== MOUNTAINS (12 listings) =====
  {
    title: "Aspen Ski Cabin",
    description: "Premier ski-in/ski-out cabin in Aspen. Mountain views, hot tub, and luxury finishes. World-class skiing at your doorstep.",
    image: { filename: "mountains-aspen-cabin-1", url: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&q=60" },
    price: 4500,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
    avgRating: 4.9,
    numReviews: 67
  },
  {
    title: "Swiss Chalet Verbier",
    description: "Iconic Swiss chalet in Verbier. Traditional architecture, modern luxury, and Alpine adventure. The ultimate mountain escape.",
    image: { filename: "mountains-verbier-chalet-1", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=60" },
    price: 5200,
    location: "Verbier",
    country: "Switzerland",
    category: "Mountains",
    avgRating: 4.9,
    numReviews: 45
  },
  {
    title: "Banff Lake Cabin",
    description: "Picturesque cabin beside Lake Louise. Mountain panoramas, wildlife viewing, and hiking trails. Canadian Rockies at their finest.",
    image: { filename: "mountains-banff-cabin-1", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=60" },
    price: 2800,
    location: "Banff",
    country: "Canada",
    category: "Mountains",
    avgRating: 4.8,
    numReviews: 123
  },
  {
    title: "Dolomites Hut Cortina",
    description: "Mountain refuge in the Italian Dolomites. Dramatic peaks, via ferrata access, and authentic Alpine cuisine. Outdoor adventure paradise.",
    image: { filename: "mountains-dolomites-hut-1", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=60" },
    price: 1950,
    location: "Cortina d'Ampezzo",
    country: "Italy",
    category: "Mountains",
    avgRating: 4.7,
    numReviews: 89
  },
  {
    title: "Queenstown Alpine Lodge",
    description: "Stunning lodge in adventure capital Queenstown. Lake views, jet boat access, and bungee jumping nearby. New Zealand's best outdoor base.",
    image: { filename: "mountains-queenstown-lodge-1", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=60" },
    price: 2200,
    location: "Queenstown",
    country: "New Zealand",
    category: "Mountains",
    avgRating: 4.8,
    numReviews: 156
  },
  {
    title: "Patagonia Refugio",
    description: "Remote refuge at foot of Torres del Paine. Glacier views, trekking access, and wilderness immersion. One of Earth's last frontiers.",
    image: { filename: "mountains-patagonia-refugio-1", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=60" },
    price: 1600,
    location: "Torres del Paine",
    country: "Chile",
    category: "Mountains",
    avgRating: 4.9,
    numReviews: 34
  },
  {
    title: "Himalaya Teahouse Nepal",
    description: "Classic teahouse on Everest trek route. Mountain panoramas, warm hospitality, and Sherpa culture. Once in a lifetime Himalayan experience.",
    image: { filename: "mountains-nepal-teahouse-1", url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=60" },
    price: 450,
    location: "Namche Bazaar",
    country: "Nepal",
    category: "Mountains",
    avgRating: 4.8,
    numReviews: 67
  },
  {
    title: "Rocky Mountain Cabin Colorado",
    description: "Authentic log cabin in Rocky Mountain National Park. Wildlife, hiking, and mountain serenity. Colorado's best mountain retreat.",
    image: { filename: "mountains-colorado-cabin-1", url: "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800&q=60" },
    price: 1850,
    location: "Estes Park",
    country: "United States",
    category: "Mountains",
    avgRating: 4.7,
    numReviews: 198
  },
  {
    title: "Pyrenees Chalet Spain",
    description: "Stone chalet in Spanish Pyrenees. Skiing in winter, hiking in summer, and border views. Hidden gem of European mountains.",
    image: { filename: "mountains-pyrenees-chalet-1", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=60" },
    price: 1450,
    location: "Baqueira-Beret",
    country: "Spain",
    category: "Mountains",
    avgRating: 4.6,
    numReviews: 78
  },
  {
    title: "Scottish Highlands Bothy",
    description: "Remote bothy in the Scottish Highlands. Wild scenery, Munro bagging, and total isolation. For serious mountain lovers only.",
    image: { filename: "mountains-scotland-bothy-1", url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=60" },
    price: 350,
    location: "Glen Affric",
    country: "United Kingdom",
    category: "Mountains",
    avgRating: 4.5,
    numReviews: 45
  },
  {
    title: "Canadian Rockies Log Cabin",
    description: "Classic log cabin in Banff National Park. Bear sightings, hot springs, and Icefields access. Iconic Canadian mountain experience.",
    image: { filename: "mountains-canada-logcabin-1", url: "https://images.unsplash.com/photo-1505852679233-d9fd70aff56d?w=800&q=60" },
    price: 2400,
    location: "Canmore",
    country: "Canada",
    category: "Mountains",
    avgRating: 4.8,
    numReviews: 167
  },
  {
    title: "New Zealand Fiord Lodge",
    description: "Luxury lodge at Milford Sound. Fjords, kayaking, and helicopter flights. Most scenic place on Earth just outside your window.",
    image: { filename: "mountains-nz-fiord-lodge-1", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=60" },
    price: 3800,
    location: "Milford Sound",
    country: "New Zealand",
    category: "Mountains",
    avgRating: 4.9,
    numReviews: 89
  },

  // ===== BEACHFRONT (12 listings) =====
  {
    title: "Cancun Beach Condo",
    description: "Beachfront condo with Caribbean views. Pool, white sand, and Caribbean blue waters. Ultimate Mexican beach vacation.",
    image: { filename: "beachfront-cancun-condo-1", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=60" },
    price: 1800,
    location: "Cancun",
    country: "Mexico",
    category: "Beachfront",
    avgRating: 4.6,
    numReviews: 234
  },
  {
    title: "Maldives Overwater Bungalow",
    description: "Iconic overwater bungalow in the Maldives. Glass floor, private deck, and infinite ocean views. The world's most desired beach accommodation.",
    image: { filename: "beachfront-maldives-bungalow-1", url: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=60" },
    price: 8500,
    location: "North Malé Atoll",
    country: "Maldives",
    category: "Beachfront",
    avgRating: 4.9,
    numReviews: 78
  },
  {
    title: "Santorini Cliff Villa",
    description: "Cave villa perched on Santorini caldera. Blue domes, sunset views, and infinity pool. Greece's most photographed destination.",
    image: { filename: "beachfront-santorini-cliff-1", url: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=60" },
    price: 4500,
    location: "Oia",
    country: "Greece",
    category: "Beachfront",
    avgRating: 4.9,
    numReviews: 156
  },
  {
    title: "Bali Seminyak Villa",
    description: "Luxury villa in Seminyak beach district. Private pool, spa treatments, and beach club access. Bali's most sophisticated beach area.",
    image: { filename: "beachfront-bali-seminyak-1", url: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800&q=60" },
    price: 2200,
    location: "Seminyak",
    country: "Indonesia",
    category: "Beachfront",
    avgRating: 4.7,
    numReviews: 267
  },
  {
    title: "Maui Oceanfront Cottage",
    description: "Charming cottage on Maui beach. Whales in winter, surf breaks, and Haleakala views. Hawaiian beach living at its finest.",
    image: { filename: "beachfront-maui-cottage-1", url: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=60" },
    price: 2800,
    location: "Maui",
    country: "United States",
    category: "Beachfront",
    avgRating: 4.8,
    numReviews: 189
  },
  {
    title: "Phuket Private Beach",
    description: "Exclusive villa on private Phuket beach. No neighbors, total privacy, and Thai hospitality. The ultimate beach escape.",
    image: { filename: "beachfront-phuket-villa-1", url: "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?w=800&q=60" },
    price: 3200,
    location: "Phuket",
    country: "Thailand",
    category: "Beachfront",
    avgRating: 4.7,
    numReviews: 145
  },
  {
    title: "Barbados Rum Shack",
    description: "Beachfront rum shack in Caribbean paradise. Local vibes, cricket on the beach, and rum punches. Authentic Barbados experience.",
    image: { filename: "beachfront-barbados-shack-1", url: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=60" },
    price: 1400,
    location: "St. Lawrence Gap",
    country: "Barbados",
    category: "Beachfront",
    avgRating: 4.6,
    numReviews: 98
  },
  {
    title: "Croatia Island Villa",
    description: "Stone villa on Dalmatian island. Crystal clear Adriatic, olive groves, and island hopping. The new Mediterranean hotspot.",
    image: { filename: "beachfront-croatia-island-1", url: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=60" },
    price: 2400,
    location: "Hvar",
    country: "Croatia",
    category: "Beachfront",
    avgRating: 4.8,
    numReviews: 112
  },
  {
    title: "Sri Lanka Surf House",
    description: "Surf camp on Sri Lanka's west coast. Consistent waves, local food, and surfing lessons. Asia's best-kept surf secret.",
    image: { filename: "beachfront-srilanka-surf-1", url: "https://images.unsplash.com/photo-1537519646063-05a1b1297d57?w=800&q=60" },
    price: 850,
    location: "Arugam Bay",
    country: "Sri Lanka",
    category: "Beachfront",
    avgRating: 4.7,
    numReviews: 178
  },
  {
    title: "Zanzibar Spice Beach",
    description: "Beachfront spice plantation villa. Turquoise water, spice tours, and dhow sailing. Exotic East African beach retreat.",
    image: { filename: "beachfront-zanzibar-spice-1", url: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=60" },
    price: 1900,
    location: "Zanzibar",
    country: "Tanzania",
    category: "Beachfront",
    avgRating: 4.8,
    numReviews: 87
  },
  {
    title: "Nosy Be Madagascar",
    description: "Island villa on Madagascar's beach paradise. Lemurs, chameleons, and perfect beaches. Off-the-beaten-path beach luxury.",
    image: { filename: "beachfront-madagascar-nosybe-1", url: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=60" },
    price: 1650,
    location: "Nosy Be",
    country: "Madagascar",
    category: "Beachfront",
    avgRating: 4.7,
    numReviews: 56
  },
  {
    title: "Bora Bora Overwater",
    description: "Famous overwater bungalow in Bora Bora. Mount Otemanu views, lagoon swimming, and honeymoon dreams. The world's most romantic resort.",
    image: { filename: "beachfront-borabora-overwater-1", url: "https://images.unsplash.com/photo-1589979481223-deb893043163?w=800&q=60" },
    price: 9500,
    location: "Bora Bora",
    country: "French Polynesia",
    category: "Beachfront",
    avgRating: 4.9,
    numReviews: 123
  },

  // ===== AMAZING POOL (12 listings) =====
  {
    title: "Bali Infinity Pool",
    description: "Villa with famous infinity pool overlooking rice terraces. World's most Instagrammed pool. Tropical luxury at its finest.",
    image: { filename: "pool-bali-infinity-1", url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=60" },
    price: 3500,
    location: "Ubud",
    country: "Indonesia",
    category: "Amazing Pool",
    avgRating: 4.9,
    numReviews: 345
  },
  {
    title: "Miami Olympic Villa",
    description: "Villa with Olympic-size pool in Miami. Water slide, cabanas, and South Beach views. Ultimate party pool destination.",
    image: { filename: "pool-miami-olympic-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=60" },
    price: 8500,
    location: "Miami",
    country: "United States",
    category: "Amazing Pool",
    avgRating: 4.7,
    numReviews: 89
  },
  {
    title: "Ibiza Cliffside Pool",
    description: "Pool carved into Ibiza cliffs. Sunset parties, Mediterranean views, and world-famous nightlife. Island of extremes.",
    image: { filename: "pool-ibiza-cliffside-1", url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=60" },
    price: 4800,
    location: "Cala Comte",
    country: "Spain",
    category: "Amazing Pool",
    avgRating: 4.8,
    numReviews: 156
  },
  {
    title: "Cape Town Rooftop Pool",
    description: "Rooftop pool with Table Mountain views. City below, mountain above, and African sky. Cape Town's best view.",
    image: { filename: "pool-capetown-rooftop-1", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=60" },
    price: 2200,
    location: "Cape Town",
    country: "South Africa",
    category: "Amazing Pool",
    avgRating: 4.8,
    numReviews: 234
  },
  {
    title: "Thailand Jungle Pool",
    description: "Pool hidden in Thai jungle. Waterfalls, nature, and total seclusion. Jungle plunge into paradise.",
    image: { filename: "pool-thailand-jungle-1", url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=60" },
    price: 1800,
    location: "Khao Sok",
    country: "Thailand",
    category: "Amazing Pool",
    avgRating: 4.9,
    numReviews: 178
  },
  {
    title: "Mykonos Infinity Edge",
    description: "Infinity pool with Aegean views in Mykonos. White everything, celebrity spotting, and sunset views. Greek island luxury.",
    image: { filename: "pool-mykonos-infinity-1", url: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=60" },
    price: 4200,
    location: "Mykonos",
    country: "Greece",
    category: "Amazing Pool",
    avgRating: 4.8,
    numReviews: 198
  },
  {
    title: "Mexico Cenote Villa",
    description: "Villa with natural cenote pool. Swimming in ancient sinkholes, jungles, and Maya ruins. Yucatan's unique water experience.",
    image: { filename: "pool-mexico-cenote-1", url: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&q=60" },
    price: 2600,
    location: "Tulum",
    country: "Mexico",
    category: "Amazing Pool",
    avgRating: 4.9,
    numReviews: 167
  },
  {
    title: "Portugal Cliff Pool",
    description: "Pool on dramatic Portuguese cliffs. Atlantic waves, dolphin watching, and surf. Europe's best-kept coast secret.",
    image: { filename: "pool-portugal-cliff-1", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=60" },
    price: 2100,
    location: "Sagres",
    country: "Portugal",
    category: "Amazing Pool",
    avgRating: 4.7,
    numReviews: 123
  },
  {
    title: "California Desert Pool",
    description: "Pool in Palm Springs desert. Mid-century modern, mountain views, and pool parties. Desert glamour meets Hollywood.",
    image: { filename: "pool-california-desert-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=60" },
    price: 2400,
    location: "Palm Springs",
    country: "United States",
    category: "Amazing Pool",
    avgRating: 4.7,
    numReviews: 145
  },
  {
    title: "Vietnam Rice Terrace Pool",
    description: "Pool overlooking Vietnamese rice terraces. Mountain mist, buffalo sightings, and terraced fields. Northern Vietnam magic.",
    image: { filename: "pool-vietnam-rice-1", url: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=60" },
    price: 1200,
    location: "Sapa",
    country: "Vietnam",
    category: "Amazing Pool",
    avgRating: 4.8,
    numReviews: 98
  },
  {
    title: "Morocco Riad Pool",
    description: "Traditional riad with courtyard pool in Marrakech. Zellige tiles, rooftop views, and Moroccan hospitality. Medina magic.",
    image: { filename: "pool-morocco-riad-1", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=60" },
    price: 950,
    location: "Marrakech",
    country: "Morocco",
    category: "Amazing Pool",
    avgRating: 4.7,
    numReviews: 267
  },
  {
    title: "Australia Outback Pool",
    description: "Pool in Australian Outback near Uluru. Red earth, starry skies, and Indigenous culture. Deep outback luxury.",
    image: { filename: "pool-australia-outback-1", url: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=60" },
    price: 3200,
    location: "Uluru",
    country: "Australia",
    category: "Amazing Pool",
    avgRating: 4.9,
    numReviews: 67
  },

  // ===== KITCHEN (12 listings) =====
  {
    title: "Lyon Chef Kitchen",
    description: "Apartment with professional chef's kitchen in food capital Lyon. Cooking classes, markets, and Michelin dining. French cuisine central.",
    image: { filename: "kitchen-lyon-chef-1", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=60" },
    price: 1800,
    location: "Lyon",
    country: "France",
    category: "Kitchen",
    avgRating: 4.9,
    numReviews: 134
  },
  {
    title: "Provence Organic Farm",
    description: "Farmhouse with organic kitchen in Provence. Farm-to-table meals, lavender fields, and truffle hunting. Culinary paradise.",
    image: { filename: "kitchen-provence-farm-1", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=60" },
    price: 2200,
    location: "Gordes",
    country: "France",
    category: "Kitchen",
    avgRating: 4.9,
    numReviews: 89
  },
  {
    title: "Sicily Pasta Villa",
    description: "Villa with pasta-making kitchen in Sicily. Nonna's recipes, local ingredients, and sea views. Authentic Italian culinary experience.",
    image: { filename: "kitchen-sicily-pasta-1", url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=60" },
    price: 1950,
    location: "Cefalù",
    country: "Italy",
    category: "Kitchen",
    avgRating: 4.8,
    numReviews: 156
  },
  {
    title: "Mexico Taco Hacienda",
    description: "Historic hacienda with authentic Mexican kitchen. Taco lessons, mezcal tasting, and colonial charm. Culinary heritage experience.",
    image: { filename: "kitchen-mexico-taco-1", url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=60" },
    price: 1400,
    location: "Oaxaca",
    country: "Mexico",
    category: "Kitchen",
    avgRating: 4.8,
    numReviews: 198
  },
  {
    title: "Smoky Mountains BBQ Cabin",
    description: "Cabin with professional BBQ setup in Tennessee. Smoker, pork shoulder, and Appalachian trails. Southern BBQ pilgrimage.",
    image: { filename: "kitchen-tennessee-bbq-1", url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=60" },
    price: 1100,
    location: "Gatlinburg",
    country: "United States",
    category: "Kitchen",
    avgRating: 4.7,
    numReviews: 167
  },
  {
    title: "Japanese Sushi Loft",
    description: "Modern loft with sushi-grade kitchen in Tokyo. Knife skills, sake pairing, and Tsukiji access. Ultimate sushi experience.",
    image: { filename: "kitchen-tokyo-sushi-1", url: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=60" },
    price: 2400,
    location: "Tokyo",
    country: "Japan",
    category: "Kitchen",
    avgRating: 4.9,
    numReviews: 234
  },
  {
    title: "Indian Spice Kitchen Goa",
    description: "Beach house with Indian spice kitchen in Goa. Curry lessons, spice market visits, and beach dining. Indian coastal cuisine.",
    image: { filename: "kitchen-goa-indian-1", url: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=60" },
    price: 850,
    location: "Goa",
    country: "India",
    category: "Kitchen",
    avgRating: 4.7,
    numReviews: 145
  },
  {
    title: "Turkish Meze Istanbul",
    description: "Bosphorus apartment with Turkish meze kitchen. mezze spread, Istanbul views, and culinary traditions. Ottoman cuisine central.",
    image: { filename: "kitchen-istanbul-turkish-1", url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=60" },
    price: 1600,
    location: "Istanbul",
    country: "Turkey",
    category: "Kitchen",
    avgRating: 4.8,
    numReviews: 178
  },
  {
    title: "Greek Cooking Island",
    description: "Cycladic house with Greek cooking kitchen. Moussaka, fresh seafood, and sunset dinners. Aegean culinary simplicity.",
    image: { filename: "kitchen-greek-island-1", url: "https://images.unsplash.com/photo-1534422298391-e4f8c172dd57?w=800&q=60" },
    price: 1300,
    location: "Paros",
    country: "Greece",
    category: "Kitchen",
    avgRating: 4.8,
    numReviews: 123
  },
  {
    title: "Peruvian Ceviche Lima",
    description: "Miraflores apartment with Peruvian kitchen. Ceviche masterclass, pisco sour, and Pacific views. Latin America's top cuisine.",
    image: { filename: "kitchen-lima-peruvian-1", url: "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?w=800&q=60" },
    price: 1400,
    location: "Lima",
    country: "Peru",
    category: "Kitchen",
    avgRating: 4.9,
    numReviews: 189
  },
  {
    title: "Thai Street Food Bangkok",
    description: "Modern Bangkok apartment with Thai street food kitchen. Pad Thai, market tours, and rooftop dining. Bangkok's best flavors.",
    image: { filename: "kitchen-bangkok-thai-1", url: "https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800&q=60" },
    price: 950,
    location: "Bangkok",
    country: "Thailand",
    category: "Kitchen",
    avgRating: 4.7,
    numReviews: 267
  },
  {
    title: "Italian Pizza Naples",
    description: "Naples apartment with wood-fired pizza oven. Pizza lessons, local ingredients, and Mount Vesuvius views. Pizza birthplace perfection.",
    image: { filename: "kitchen-naples-pizza-1", url: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=60" },
    price: 1650,
    location: "Naples",
    country: "Italy",
    category: "Kitchen",
    avgRating: 4.9,
    numReviews: 234
  },

  // ===== DESIGN (12 listings) =====
  {
    title: "Portland Treehouse",
    description: "Architecturally stunning treehouse in Portland. Cantilever design, forest views, and innovative sustainability. Treehouse engineering marvel.",
    image: { filename: "design-portland-treehouse-1", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=60" },
    price: 2800,
    location: "Portland",
    country: "United States",
    category: "Design",
    avgRating: 4.9,
    numReviews: 78
  },
  {
    title: "Copenhagen Glass Pavilion",
    description: "Contemporary glass house in Copenhagen. Transparency, light, and Nordic minimalism. Architecture as experience.",
    image: { filename: "design-copenhagen-glass-1", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=60" },
    price: 3200,
    location: "Copenhagen",
    country: "Denmark",
    category: "Design",
    avgRating: 4.8,
    numReviews: 56
  },
  {
    title: "Joshua Tree Dome",
    description: "Geodesic dome in Joshua Tree desert. Solar-powered, stargazing ceiling, and desert minimalism. Architectural desert retreat.",
    image: { filename: "design-joshuatree-dome-1", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=60" },
    price: 2400,
    location: "Joshua Tree",
    country: "United States",
    category: "Design",
    avgRating: 4.8,
    numReviews: 167
  },
  {
    title: "Cape Town Container",
    description: "Converted shipping container in Cape Town. Industrial chic, rooftop deck, and Table Mountain views. Sustainable design success.",
    image: { filename: "design-capetown-container-1", url: "https://images.unsplash.com/photo-1600210492493-0946913c3316?w=800&q=60" },
    price: 1800,
    location: "Cape Town",
    country: "South Africa",
    category: "Design",
    avgRating: 4.7,
    numReviews: 89
  },
  {
    title: "Taos Earthship",
    description: "Fully sustainable earthship in New Mexico. Recycled materials, passive solar, and desert independence. Future living now.",
    image: { filename: "design-taos-earthship-1", url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&q=60" },
    price: 1600,
    location: "Taos",
    country: "United States",
    category: "Design",
    avgRating: 4.8,
    numReviews: 123
  },
  {
    title: "Dutch Cube House",
    description: "Rotterdam cube house with upside-down design. Living in architecture, harbor views, and Dutch innovation. True architectural experience.",
    image: { filename: "design-rotterdam-cube-1", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=60" },
    price: 2100,
    location: "Rotterdam",
    country: "Netherlands",
    category: "Design",
    avgRating: 4.7,
    numReviews: 145
  },
  {
    title: "Barcelona Gaudi Inspired",
    description: "Gaudi-influenced apartment in Barcelona. Organic curves, mosaic details, and Eixample views. Catalan design legacy.",
    image: { filename: "design-barcelona-gaudi-1", url: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=60" },
    price: 2600,
    location: "Barcelona",
    country: "Spain",
    category: "Design",
    avgRating: 4.9,
    numReviews: 198
  },
  {
    title: "Frank Lloyd Wright Cabin",
    description: "Cabin inspired by Frank Lloyd Wright in Wisconsin. Organic architecture, forest setting, and design history. American architectural icon.",
    image: { filename: "design-wisconsin-flw-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=60" },
    price: 2200,
    location: "Spring Green",
    country: "United States",
    category: "Design",
    avgRating: 4.8,
    numReviews: 67
  },
  {
    title: "Bubble House France",
    description: "Transparent bubble in French Alps. 360-degree mountain views and unique design. Sleep under the Alps.",
    image: { filename: "design-france-bubble-1", url: "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=60" },
    price: 1900,
    location: "Chamonix",
    country: "France",
    category: "Design",
    avgRating: 4.8,
    numReviews: 89
  },
  {
    title: "A Frame Alaska",
    description: "Classic A-frame cabin in Alaskan wilderness. Glass walls, forest setting, and northern lights. Back to nature design.",
    image: { filename: "design-alaska-aframe-1", url: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=800&q=60" },
    price: 1700,
    location: "Talkeetna",
    country: "United States",
    category: "Design",
    avgRating: 4.7,
    numReviews: 112
  },
  {
    title: "Yurt Mongolia Style",
    description: "Modern yurt on Montana ranch. Nomadic design, star roof, and ranch life. Mongolian tradition meets American West.",
    image: { filename: "design-montana-yurt-1", url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=60" },
    price: 1200,
    location: "Montana",
    country: "United States",
    category: "Design",
    avgRating: 4.7,
    numReviews: 156
  },
  {
    title: "Sauna Finland Modern",
    description: "Architectural sauna house in Finnish lakefront. Glass walls, smoke sauna, and design excellence. Sauna as art.",
    image: { filename: "design-finland-sauna-1", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=60" },
    price: 2400,
    location: "Kuopio",
    country: "Finland",
    category: "Design",
    avgRating: 4.9,
    numReviews: 78
  },

  // ===== FAVORITES (12 listings) =====
  {
    title: "Cotswolds Cottage UK",
    description: "Quintessential Cotswolds stone cottage. Honey-stone walls, garden, and pub walks. England's most beloved countryside.",
    image: { filename: "favorites-cotswolds-1", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=60" },
    price: 1850,
    location: "Bourton-on-the-Water",
    country: "United Kingdom",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 234
  },
  {
    title: "Lake Como Villa",
    description: "Historic villa on Lake Como. Bellagio views, gardens, and celebrity spotting. Italian lake luxury at its best.",
    image: { filename: "favorites-lakecomo-1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=60" },
    price: 5500,
    location: "Bellagio",
    country: "Italy",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 189
  },
  {
    title: "Amalfi Cliff House",
    description: "Cliff house on Amalfi Coast. Vertical gardens, sea views, and lemon trees. Italy's most dramatic coastline.",
    image: { filename: "favorites-amalfi-1", url: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=60" },
    price: 4200,
    location: "Positano",
    country: "Italy",
    category: "Favorites",
    avgRating: 4.8,
    numReviews: 156
  },
  {
    title: "Skye Castle Scotland",
    description: "Castle on Isle of Skye. Dramatic landscapes, history, and isolation. Scotland's most magical destination.",
    image: { filename: "favorites-skye-castle-1", url: "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=800&q=60" },
    price: 3200,
    location: "Isle of Skye",
    country: "United Kingdom",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 78
  },
  {
    title: "Lake Louise Cabin",
    description: "Cabin at Lake Louise in Banff. Turquoise water, mountain backdrop, and wildlife. Canada's most iconic view.",
    image: { filename: "favorites-lakelouise-1", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=60" },
    price: 2800,
    location: "Lake Louise",
    country: "Canada",
    category: "Favorites",
    avgRating: 4.8,
    numReviews: 267
  },
  {
    title: "Hallstatt Lake Austria",
    description: "Fairy-tale house on Hallstatt Lake. UNESCO site, salt mining history, and Alpine views. Europe's most beautiful village.",
    image: { filename: "favorites-hallstatt-1", url: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec3?w=800&q=60" },
    price: 2400,
    location: "Hallstatt",
    country: "Austria",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 145
  },
  {
    title: "Santorini Caldera Suite",
    description: "Caldera suite with best sunset views in Santorini. Blue domes, volcanic cliffs, and romance. Greece's most famous view.",
    image: { filename: "favorites-santorini-caldera-1", url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=60" },
    price: 3800,
    location: "Oia",
    country: "Greece",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 312
  },
  {
    title: "Matera Cave Hotel",
    description: "Hotel carved into Matera caves. Ancient cave dwellings, rock churches, and UNESCO status. Italy's oldest city, most unique stay.",
    image: { filename: "favorites-matera-1", url: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=60" },
    price: 1600,
    location: "Matera",
    country: "Italy",
    category: "Favorites",
    avgRating: 4.8,
    numReviews: 189
  },
  {
    title: "Faroe Islands Cottage",
    description: "Cottage on Faroe Islands. Dramatic cliffs, grass-roof houses, and isolation. Europe's best-kept secret destination.",
    image: { filename: "favorites-faroe-1", url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=60" },
    price: 2100,
    location: "Gásadalur",
    country: "Faroe Islands",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 67
  },
  {
    title: "Slovenia Lake Bled",
    description: "Castle perched above Lake Bled. Island church, row boats, and Alpine peaks. Slovenia's most iconic sight.",
    image: { filename: "favorites-bled-1", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=800&q=60" },
    price: 2200,
    location: "Lake Bled",
    country: "Slovenia",
    category: "Favorites",
    avgRating: 4.8,
    numReviews: 234
  },
  {
    title: "Iceland Hot Spring Villa",
    description: "Villa with private hot spring in Iceland. Northern lights, lava fields, and Blue Lagoon access. Fire and ice land.",
    image: { filename: "favorites-iceland-hotspring-1", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=60" },
    price: 4500,
    location: "Reykjavik",
    country: "Iceland",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 145
  },
  {
    title: "Patagonia Glamping",
    description: "Luxury glamping at Torres del Paine. Hiking, glaciers, and wildlife. World's end in comfort.",
    image: { filename: "favorites-patagonia-glamping-1", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=60" },
    price: 3200,
    location: "Torres del Paine",
    country: "Chile",
    category: "Favorites",
    avgRating: 4.9,
    numReviews: 98
  }
];

module.exports = { data };